#!/bin/bash
cd backend
#composer update
composer install
php app/console cache:clear --env=prod --no-debug
php app/console cache:clear --env=dev --no-debug

php app/console doctrine:database:drop --force
php app/console doctrine:database:create
php app/console doctrine:schema:update --force
php app/console doctrine:fixtures:load

cd ..