login_controller:
    type: rest
    resource: ZPIBundle\Controller\LoginController

showPicture_controller:
    type: rest
    resource: ZPIBundle\Controller\ShowPictureController

chooseCategory_controller:
    type: rest
    resource: ZPIBundle\Controller\ChooseCategoryController

checkAnswer_controller:
    type: rest
    resource: ZPIBundle\Controller\CheckAnswerController

statistics_controller:
    type: rest
    resource: ZPIBundle\Controller\StatisticsController