login_controller:
    type: rest
    resource: ZPIBundle\Controller\LoginController

showPicture_controller:
    type: rest
    resource: ZPIBundle\Controller\ShowPictureController

chooseCategory_controller:
    type: rest
    resource: ZPIBundle\Controller\ChooseCategoryController

checkAnswer_controller:
    type: rest
    resource: ZPIBundle\Controller\CheckAnswerController

teacherPanel_controller:
    type: rest
    prefix: /panel
    resource: ZPIBundle\Controller\TeacherPanelController

statistics_controller:
    type: rest
    resource: ZPIBundle\Controller\StatisticsController
