login_controller:
    type: rest
    resource: ZPIBundle\Controller\LoginController
showPicture_controller:
    type: rest
    resource: ZPIBundle\Controller\ShowPictureController
chooseCategory_controller:
    type: rest
    resource: ZPIBundle\Controller\ChooseCategoryController